<a href="https://colab.research.google.com/github/alecoder1/PyTorch-Tutorial/blob/main/Tensor_ops_(Reshape_%26_View).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TENSOR MATH OPERATIONS
- Add, Substract, Multiply, Divide, Remainders, Exponents
- Shorthand and uh, longhand
- Reassignment

In [23]:
import torch
import numpy as np

In [24]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [25]:
# Addiction
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [7]:
# subtraction longhand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [8]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# mul longhand
torch.mul(tensor_a, tensor_b)


tensor([ 5, 12, 21, 32])

In [10]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [11]:
# Div longhand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [13]:
# Reminder Modulus
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [14]:
# Remainder longhand
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [15]:
# Exponents / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [16]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a

tensor([1, 2, 3, 4])

In [21]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([ 6,  8, 10, 12])