<a href="https://colab.research.google.com/github/alecoder1/PyTorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TENSORS

- A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar To Numpy Arrays, but full of fun things that make work better on GPU's (vs regular CPU'S).
- default data type of float32.
- More suitable for deep learning than a numpy array.

In [2]:
import torch
import numpy as np

## LISTS

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.41969265, 0.1907633 , 0.67107311, 0.8440861 ],
       [0.7728233 , 0.12992235, 0.41517129, 0.58865025],
       [0.33053358, 0.36796716, 0.50629439, 0.73015378]])

In [6]:
np1.dtype

dtype('float64')

In [8]:
np2 = np.random.rand(3)
np2

array([0.85752418, 0.68037076, 0.43679039])

In [9]:
np2.dtype

dtype('float64')

## TENSORS

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# Create tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4197, 0.1908, 0.6711, 0.8441],
        [0.7728, 0.1299, 0.4152, 0.5887],
        [0.3305, 0.3680, 0.5063, 0.7302]], dtype=torch.float64)